package:
  name: meld-dev-test
  version: {{ environ['VERSTRING'] }}

source:
  path: /io # [linux]
  path: /Users/travis/build/maccallumlab/meld #[osx]

requirements:
  build:
    - openmm-cuda{{ CUDA_SHORT_VERSION }} ==7.2.2
    - cmake
    - doxygen # [not osx]
    - python
    - swig
    - eigen3
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - sphinx
    - sphinx_rtd_theme ==0.1.9
    - mpi4py
    - clangdev ==6.0.0
    - mypy

  run:
    - python
    - openmm-cuda{{ CUDA_SHORT_VERSION }} ==7.2.2
    - ambermini
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - mpi4py
    - scikit-learn >=0.18.0

test:
  requires:
    - mypy
  imports:
    - meld
    - meldplugin
  commands:
    - python -m unittest discover meld.test
    - mypy /io/meld

about:
    home: https://meldmd.org
