#!/usr/bin/env python
# encoding: utf-8


import argparse
from meld.remd import launch


def main():
    parser = argparse.ArgumentParser(
        description='Launch replica exchange run.')
    parser.parse_args()

    launch.launch()


if __name__ == '__main__':
    main()
